### ISSUE TITLE
return school IDs for school search results and favorite schools

### ISSUE THREAD

**Issue by geomcmaster** [geomcmaster/CollegeMatch#17]
When returning a list of schools (favorites or search results), we should populate the School objects with the school IDs. This way, when a user opens the details page for a school, we can pass the school ID to a method that will execute a query returning detailed results for said school.

**Comment by geomcmaster** [comment]
1. add field to School class
2. add school.ID column to select clause for getSchools()
3. similarly, add school.ID column to select clause for get_favorite_schools stored procedure
4. have getSchools() and getFavoriteSchools() populate the ID field in the school object when processing results

**Comment by jsung23** [comment]
Did #1 and #2. 
3. Where is the stored procedure located in the code? I changed it in the checkpoint.
4. Changed get Schools, but where's getFavoriteSchools()?

**Comment by geomcmaster** [comment]
- It's not in the code. Go to MySQL workbench and you should be able to find a list of stored procedures for the CollegeMatch database. Edit it then press Apply or whatever the button is.
- Maybe it's called getFavSchools()

**Comment by jsung23** [comment]
Weird i don't see the stored procedure on the left navigation pane. Only
the create table 1-3 procedures

**Comment by geomcmaster** [comment]
Because you never added it. You have to create the three stored procedures from the checkpoint.

**Comment by jsung23** [comment]
Done!

**Comment by geomcmaster** [comment]
Let's close when the pull request is merged :)
You can add this issue when you submit the PR https://github.com/blog/1506-closing-issues-via-pull-requests
