### ISSUE TITLE
Add method to return Condition for if school has user-selected field in its top 5 programs

### ISSUE THREAD

**Issue by jsung23** [geomcmaster/CollegeMatch#37]

**Comment by VersorVerbi** [comment]
You can do that, but for the moment, it's a pretty simple OR_GROUP Condition that I have set up.

**Comment by geomcmaster** [comment]
In that case @jsung23, maybe just instead write a test case that checks that @VersorVerbi's way of creating the condition returns results we would expect.

**Comment by jsung23** [comment]
Just read this. I've been done with the method for a while. Just need to
finish up the junit test method. So I'll just keep what I've done
