### ISSUE TITLE
Search options don't have entry fields

### ISSUE THREAD

**Issue by geomcmaster** [geomcmaster/CollegeMatch#51]

**Comment by VersorVerbi** [comment]
Which ones? When does this happen?

**Comment by VersorVerbi** [comment]
Just saw median debt doesn't. Any others?

**Comment by geomcmaster** [comment]
All of them.

**Comment by geomcmaster** [comment]
I'm not sure what commit it was.

**Comment by VersorVerbi** [comment]
That's weird. I don't think I've seen that at all.

**Comment by geomcmaster** [comment]
Closing as I'm only encountering this within eclipse.
