### ISSUE TITLE
School object's Location is not null, but isLocationNotNull returns false

### ISSUE THREAD

**Issue by VersorVerbi** [geomcmaster/CollegeMatch#65]
When I search, each returned School object has an associated Location with data in it, but the School object's "isLocationNotNull()" function returns false, so I don't get that Location data. At some point, each object needs to setLocationIsNotNull(true).

**Comment by geomcmaster** [comment]
![image](https://user-images.githubusercontent.com/11367332/28978627-49f8838a-790c-11e7-8675-4e8366937f6f.png)
Looks like my bad. I can take this.

**Comment by VersorVerbi** [comment]
This also needs to be corrected in UserDAO for retrieving the Location of favorite schools.
