### ISSUE TITLE
don't display rank of 0

### ISSUE THREAD

**Issue by geomcmaster** [geomcmaster/CollegeMatch#86]
When a favorite is added, it has a rank of 0, which is meaningless.

**Comment by VersorVerbi** [comment]
Yeah, I was debating whether I should try to make it sequentially the last in the list (which would require querying for the list, counting them, then adding one) or if it would be easier to do that during the add-a-favorite process on the server side.

The other problem is that there's currently no way to ensure that each rank is unique for a user.
